### ISSUE TITLE
Question about evaluating the checkpoint on the ObjectGoal Navigation task.

### ISSUE THREAD

**Issue by yuerbujin** [Ram81/habitat-imitation-baselines#13] opened 2023-04-17 13:09 UTC
hello @Ram81,

i want to evaluate the [checkpoint](https://habitat-on-web.s3.amazonaws.com/release/checkpoints/objectnav/objectnav_semseg.ckpt) on the ObjectGoal Navigation task. I use the following command

```python
python -u -m habitat_baselines.run \
--exp-config  habitat_baselines/config/objectnav/il_objectnav.yaml \
--run-type eval \
TASK_CONFIG.DATASET.DATA_PATH "data/datasets/objectnav/objectnav_mp3d_70k/train/train.json.gz" \
TASK_CONFIG.TASK.SENSORS "['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']" \
EVAL_CKPT_PATH_DIR data/checkpoint/objectnav_semseg.ckpt
``` 

but i got the following error.

```
2023-04-17 20:49:13,081 Initializing dataset ObjectNav-v1
/home/test/.conda/envs/habitat-web/lib/python3.6/site-packages/gym/core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
2023-04-17 20:49:15,170 Initializing dataset ObjectNav-v1
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/core/vector_env.py", line 196, in _worker_env
    env = env_fn(*env_fn_args)
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/utils/env_utils.py", line 29, in make_env_fn
    config.TASK_CONFIG.DATASET.TYPE, config=config.TASK_CONFIG.DATASET
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/datasets/registration.py", line 21, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/datasets/object_nav/object_nav_dataset.py", line 93, in __init__
    super().__init__(config)
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/datasets/pointnav/pointnav_dataset.py", line 116, in __init__
    self.from_json(f.read(), scenes_dir=config.SCENES_DIR)
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/datasets/object_nav/object_nav_dataset.py", line 158, in from_json
    episode.goals = self.goals_by_category[episode.goals_key]
KeyError: '1LXtFkjw3qL.glb_game_equipment'
Traceback (most recent call last):
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/run.py", line 79, in <module>
    main()
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/run.py", line 40, in main
    run_exp(**vars(args))
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/run.py", line 75, in run_exp
    execute_exp(config, run_type)
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/run.py", line 60, in execute_exp
    trainer.eval()
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/common/base_trainer.py", line 111, in eval
    checkpoint_index=ckpt_idx,
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/il/env_based/il_trainer.py", line 514, in _eval_checkpoint
    self.envs = construct_envs(config, get_env_class(config.ENV_NAME))
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat_baselines/utils/env_utils.py", line 102, in construct_envs
    workers_ignore_signals=workers_ignore_signals,
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/core/vector_env.py", line 157, in __init__
    read_fn() for read_fn in self._connection_read_fns
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/core/vector_env.py", line 157, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method VectorEnv.__del__ of <habitat.core.vector_env.VectorEnv object at 0x7f8cf8bc8048>>
Traceback (most recent call last):
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/core/vector_env.py", line 638, in __del__
    self.close()
  File "/media/test/data2/yjh/habitat-web/habitat-web-baselines/habitat/core/vector_env.py", line 504, in close
    write_fn((CLOSE_COMMAND, None))
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/test/.conda/envs/habitat-web/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
``` 

it says " KeyError: '1LXtFkjw3qL.glb_game_equipment' ", but i don't know how to solve it. Should i modify the file "train.json.gz"?

**Comment by me-no-money** [comment] 2023-04-19 03:16
Hi @yuerbujin, I had a similar problem some time ago. I suggest you check your scene_datasets folder setting. Mine looks like this.
![scene_datasets](https://user-images.githubusercontent.com/71805391/232957755-2c12916d-c768-462e-b782-c9c0d4a68a36.png)

**Comment by yuerbujin** [comment] 2023-04-19 08:56
> Hi @yuerbujin, I had a similar problem some time ago. I suggest you check your scene_datasets folder setting. Mine looks like this. ![scene_datasets](https://user-images.githubusercontent.com/71805391/232957755-2c12916d-c768-462e-b782-c9c0d4a68a36.png)

@me-no-money 
thanks for your reply.
I have modified my scene_datasets folder settings the same as yours. But the problem still exists and doesn't change.
![image](https://user-images.githubusercontent.com/68276188/233023336-2db2b642-4e8f-4b49-b1d6-7af4c652de79.png)

**Comment by yuerbujin** [comment] 2023-04-20 02:54
i have successfully solved this problem using the original [mp3d task dataset](https://dl.fbaipublicfiles.com/habitat/data/datasets/objectnav/m3d/v1/objectnav_mp3d_v1.zip) !

i modified the task dataset path.
```
TASK_CONFIG.DATASET.DATA_PATH "data/datasets/objectnav/mp3d/val/val.json.gz"
``` 

thanks for helping me～

**Comment by Ram81** [comment] 2023-04-21 14:46
@me-no-money you are evaluating the checkpoint on the imitation learning dataset. If you are trying to reproduce the results from the paper you should be using the original [MP3D task dataset](https://dl.fbaipublicfiles.com/habitat/data/datasets/objectnav/m3d/v1/objectnav_mp3d_v1.zip) for evaluation like @yuerbujin suggested. Please let me know if you are still facing issues

**Comment by me-no-money** [comment] 2023-04-22 04:13
Thank you for the suggestion @Ram81 . My previous mistake was because the structure of my scene_datasets folder was wrong. BTW, I want to konw if the eval-metrics of objectnav task are reasonable. I can't make the success rate >= 0.3
![objectnav-eval-tensorboard](https://user-images.githubusercontent.com/71805391/233759954-48cea722-01fa-4df3-90f3-6a272c351740.png)
And my training-metrics of objectnav task is as follows. I still need to do some parameter tuning, right?
![objectnav-train-tensorboard](https://user-images.githubusercontent.com/71805391/233760459-6b6f26b6-bebd-4f06-88ee-722125c998d1.png)

**Comment by yuerbujin** [comment] 2023-04-22 08:47
> Thank you for the suggestion @Ram81 . My previous mistake was because the structure of my scene_datasets folder was wrong. BTW, I want to konw if the eval-metrics of objectnav task are reasonable. I can't make the success rate >= 0.3 ![objectnav-eval-tensorboard](https://user-images.githubusercontent.com/71805391/233759954-48cea722-01fa-4df3-90f3-6a272c351740.png) And my training-metrics of objectnav task is as follows. I still need to do some parameter tuning, right? ![objectnav-train-tensorboard](https://user-images.githubusercontent.com/71805391/233760459-6b6f26b6-bebd-4f06-88ee-722125c998d1.png)

my train results is similar to yours(at around 10k training steps), but my eval results is much larger than yours.

maybe you can contact me via twitter? so that we can discuss this further.

**Comment by me-no-money** [comment] 2023-04-22 09:00
> > Thank you for the suggestion @Ram81 . My previous mistake was because the structure of my scene_datasets folder was wrong. BTW, I want to konw if the eval-metrics of objectnav task are reasonable. I can't make the success rate >= 0.3 ![objectnav-eval-tensorboard](https://user-images.githubusercontent.com/71805391/233759954-48cea722-01fa-4df3-90f3-6a272c351740.png) And my training-metrics of objectnav task is as follows. I still need to do some parameter tuning, right? ![objectnav-train-tensorboard](https://user-images.githubusercontent.com/71805391/233760459-6b6f26b6-bebd-4f06-88ee-722125c998d1.png)
> 
> my train results is similar to yours(at around 10k training steps), but my eval results is much larger than yours.
> 
> maybe you can contact me via twitter? so that we can discuss this further.

Nice to hear that, I am following you now @yuerbujin

**Comment by Ram81** [comment] 2023-04-30 00:41
@me-no-money can you share what training config are you using? how many updates do you train for? 

Btw I am closing this issue as it is not related to eval checkpoint bug. Feel free to open a new issue to discuss reproducing training results

**Closed as completed by Ram81** 2023-04-30 00:41 UTC
